#!/bin/bash -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )

LIBS=${DIR}/lib
LIBS=$LIBS:${DIR}/usr/lib
LIBS=$LIBS:${DIR}/home-assistant/usr/lib
LIBS=$LIBS:${DIR}/usr/local/lib
export PYTHONPATH=$DIR/usr/src/homeassistant
export PATH=${DIR}/home-assistant/bin:$PATH
${DIR}/lib/ld-musl-*.so* --library-path $LIBS ${DIR}/usr/local/bin/python3 "$@"
