default_config:

# Text to speech
tts:
  - platform: google_translate

#group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml

homeassistant:
  auth_providers:
    - type: command_line
      command: /snap/home-assistant/current/ldap-auth-sh/ldap-auth.sh
      args: ["/var/snap/home-assistant/current/config/ldap-auth.cfg"]
#   Uncomment and see below if you want the Home Assistant
#  user to be populated with his full name.
#   meta: true
